name: Hello World Training Workflow
on:
  workflow_dispatch:
  push:
    branches:
      -main
  issues:
    types: [opened,edited]
jobs:
    greet:
        env:
          MY_ENV: "John Doe"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: List repository files
            run: ls
          - name: Read README
            run: cat README.md
          - name: Greet the user
            run: echo "Hello World! from test branch"
          - name: Show environment variables
            run: |
              echo "Hello $MY_ENV"
              echo "Hello $GITHUB_ACTOR"
            
