name: CI workflow testing
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
